version: '3.7'
services:
  postgres-db:
    image: postgres:11.2
    container_name: postgresdb
    ports:
    - 5432:5432
    volumes:
      - "/Users/bhudson/dockervolumes/ocmdb:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=<default>
      - POSTGRES_USER=test
      - POSTGRES_DB=OCM
    shm_size: '256MB'
